---
- hosts: localhost

  tasks:
  - name: Add Hawkular Datawarehouse Provider to ManageIQ
    manageiq_provider:
      name: 'HawkDW01'
      provider_type: 'hawkular-datawarehouse'
      state: 'present'
      provider_api_hostname: 'hawk.example.com'
      provider_api_port: '443'
      provider_api_auth_token: '******'
      miq_url: 'http://miq.example.com'
      miq_username: 'admin'
      miq_password: '******'
      miq_verify_ssl: false
      provider_verify_ssl: false
    register: result

  - debug: var=result
