---
- hosts: localhost

  tasks:
  - name: Add Openshift Containers Provider to ManageIQ
    manageiq:
      name: '{{ name }}'
      type: '{{ type }}'
      state: '{{ state }}'
      miq_url: '{{ miq_url | default(omit) }}'
      miq_username: '{{ miq_username | default(omit) }}'
      miq_password: '{{ miq_password | default(omit) }}'
      hostname: '{{ hostname }}'
      port: '{{ port }}'
      token: '{{ token }}'
      metrics: '{{ metrics | default(omit) }}'
      hawkular_hostname: '{{ hawkular_hostname | default(omit) }}'
      hawkular_port: '{{ hawkular_port | default(omit) }}'
    register: result

  - debug: var=result
