---
- hosts: localhost

  tasks:
  - name: Add Openshift Containers Provider to ManageIQ
    manageiq_provider:
      name: '{{ name }}'
      provider_type: '{{ provider_type }}'
      state: '{{ state }}'
      miq_url: '{{ miq_url | default(omit) }}'
      miq_username: '{{ miq_username | default(omit) }}'
      miq_password: '{{ miq_password | default(omit) }}'
      provider_api_hostname: '{{ provider_api_hostname }}'
      provider_api_port: '{{ provider_api_port | default(omit) }}'
      provider_api_auth_token: '{{ provider_api_auth_token }}'
      metrics: '{{ metrics | default(omit) }}'
      hawkular_hostname: '{{ hawkular_hostname | default(omit) }}'
      hawkular_port: '{{ hawkular_port | default(omit) }}'
      verify_ssl: '{{ verify_ssl | default(True) }}'
    register: result

  - debug: var=result
