---
- hosts: hosts

  tasks:
  - name: Assign policy on an OpenShift provider in ManageIQ
    manageiq_policy_assignment:
      entity: '{{ entity }}'
      entity_name: '{{ entity_name }}'
      resource: '{{ resource }}'
      resource_name: '{{ resource_name }}'
      state: '{{ state }}'
      miq_url: '{{ miq_url | default(omit) }}'
      miq_username: '{{ miq_username | default(omit) }}'
      miq_password: '{{ miq_password | default(omit) }}'
    register: result

  - debug: var=result
