---
- hosts: localhost

  tasks:
  - name: Add Custom Attributes to Openshift containers provider
    manageiq_custom_attributes:
      entity_type: 'provider'
      entity_name: 'Openshift01'
      state: 'present'
      custom_attributes:
        - name: 'ca1'
          value: 'value 1'
        - name: 'ca2'
          value: 'value 2'
      miq_url: 'https://miq.example.com'
      miq_username: 'dkorn'
      miq_password: '******'
      miq_verify_ssl: false
    register: result

  - debug: var=result
